// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('MacOS 플랫폼은 지원되지 않습니다. iOS나 안드로이드 기기를 사용해주세요.');
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows 플랫폼은 지원되지 않습니다. iOS나 안드로이드 기기를 사용해주세요.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError('Linux 플랫폼은 지원되지 않습니다. iOS나 안드로이드 기기를 사용해주세요.');
      default:
        throw UnsupportedError('이 플랫폼은 지원되지 않습니다. iOS나 안드로이드 기기를 사용해주세요.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHyl6DN3cPJznoNoAgW7VWMT2CnUdIrk8',
    appId: '1:316890086124:web:65e70699fad4ec9567c3c9',
    messagingSenderId: '316890086124',
    projectId: 'csi-online-attendance-system',
    authDomain: 'csi-online-attendance-system.firebaseapp.com',
    storageBucket: 'csi-online-attendance-system.firebasestorage.app',
    measurementId: 'G-DHVC2W6FED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC83_ihCdQSUjmTNJRqs5yEeaejwxoPwac',
    appId: '1:316890086124:android:78e6d79deebf7b1b67c3c9',
    messagingSenderId: '316890086124',
    projectId: 'csi-online-attendance-system',
    storageBucket: 'csi-online-attendance-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApbjLzmSL1os3BSxmdEGg-5ByiMsAHxvA',
    appId: '1:316890086124:ios:51738bac68f508b267c3c9',
    messagingSenderId: '316890086124',
    projectId: 'csi-online-attendance-system',
    storageBucket: 'csi-online-attendance-system.firebasestorage.app',
    iosBundleId: 'com.example.capstonDesign',
  );
}
